esphome:
  name: esp8266-propanemonitor
  comment: {Your Comment}

esp8266:
  board: d1_mini
  framework:
    version: recommended

logger:

wifi:
  manual_ip:
    static_ip: {Your IP}
    gateway: {Your Gateway}
    subnet: {Your Subnet}
    dns1: {Your DNS}
    dns2: 0.0.0.0
  ap:
    ssid: "Fallback-PropaneMonitor"
    password: ""
    ap_timeout: 1min
  domain: {Your Domain}
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  networks:
  - ssid: {Your SSID}
    password: {Your WiFi Password}
    priority: 0.0
  use_address: {Your IP}
  
captive_portal:

ota:
  password: {Your OTA Password}
  safe_mode: true
  port: 8266

deep_sleep:
  id: deep_sleep_control
  run_duration: 5min
  sleep_duration: 10075min

mqtt:
  broker: {Your MQTT Broker}
  port: 1883
  username: {Your MQTT User}
  password: {Your MQTT Password}
  discovery: True
  discovery_retain: True
  client_id: propanemonitor
  topic_prefix: propanemonitor
  on_message:
    - topic: ota_mode
      payload: 'ON'
      then:
        - logger.log: 'OTA Mode ON - Deep sleep DISABLED'
        - deep_sleep.prevent: deep_sleep_control
    - topic: ota_mode
      payload: 'OFF'
      then:
        - logger.log: 'OTA Mode OFF - Deep sleep ENABLED'
        - deep_sleep.enter: deep_sleep_control

sensor:
- platform: adc
  pin: A0
  name: "Propane Sensor"
  update_interval: 1440min
  filters:
    - multiply: 3.3
    - lambda: return x * (31.66360585143436) + (10);
  unit_of_measurement: "%"